export const ADD_ITEM = 'ADD_ITEM';
export const EDIT_ITEM = 'EDIT_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const CANCEL_EDIT = 'CANCEL_EDIT';
export const LOAD_ITEMS_FROM_LOCALSTORAGE = 'LOAD_ITEMS_FROM_LOCALSTORAGE';
export const SET_FILTER = 'SET_FILTER';



export default {
	ADD_ITEM,
	EDIT_ITEM,
	DELETE_ITEM,
	UPDATE_ITEM,
	CANCEL_EDIT,
	LOAD_ITEMS_FROM_LOCALSTORAGE,
	SET_FILTER,
};
